### ISSUE TITLE
Need to use Multi-gpus?

### ISSUE THREAD

**Issue by Howardqlz** [JPLeoRX/detectron2-publaynet#1]
Nice works and I prepare to do some works base on Publaynet with detectron2 too. But Publaynet has too many images, I wonder your batch-size is 128, so you use 1gpu or more?

**Comment by JPLeoRX** [comment]
> Nice works and I prepare to do some works base on Publaynet with detectron2 too. But Publaynet has too many images, I wonder your batch-size is 128, so you use 1gpu or more?

Thanks and good luck with your project too!

I used only 1 GPU here - NVIDIA 2070 SUPER (8GB)

**Comment by JPLeoRX** [comment]
Closing this issue
